# Generated by Django 4.2.9 on 2025-10-23 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("change_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Scan type name (e.g., SAST, DAST, SCA)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the scan type"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this scan type is active"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Scan configuration parameters",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scan Type",
                "verbose_name_plural": "Scan Types",
                "db_table": "scan_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When the analysis was started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the analysis was completed",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Analysis notes and findings"
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        blank=True, help_text="Risk score (0-100)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analyst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_analyses",
                        to="change_requests.changerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Analysis",
                "verbose_name_plural": "Security Analyses",
                "db_table": "security_analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, help_text="Scan duration in seconds", null=True
                    ),
                ),
                (
                    "findings_count",
                    models.IntegerField(
                        default=0, help_text="Number of findings discovered"
                    ),
                ),
                (
                    "critical_count",
                    models.IntegerField(
                        default=0, help_text="Number of critical findings"
                    ),
                ),
                (
                    "high_count",
                    models.IntegerField(
                        default=0, help_text="Number of high severity findings"
                    ),
                ),
                (
                    "medium_count",
                    models.IntegerField(
                        default=0, help_text="Number of medium severity findings"
                    ),
                ),
                (
                    "low_count",
                    models.IntegerField(
                        default=0, help_text="Number of low severity findings"
                    ),
                ),
                (
                    "report_url",
                    models.URLField(
                        blank=True, help_text="URL to the scan report", null=True
                    ),
                ),
                (
                    "raw_results",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw scan results"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if scan failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scans",
                        to="security_analysis.scantype",
                    ),
                ),
                (
                    "security_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="security_analysis.securityanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan",
                "verbose_name_plural": "Scans",
                "db_table": "scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Finding title", max_length=255)),
                ("description", models.TextField(help_text="Detailed description")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("INFO", "Informational"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("FALSE_POSITIVE", "False Positive"),
                            ("ACCEPTED_RISK", "Accepted Risk"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "cwe_id",
                    models.CharField(
                        blank=True, help_text="CWE identifier", max_length=20, null=True
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="File path where the finding was discovered",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "line_number",
                    models.IntegerField(
                        blank=True, help_text="Line number in the file", null=True
                    ),
                ),
                (
                    "remediation",
                    models.TextField(blank=True, help_text="Remediation guidance"),
                ),
                (
                    "external_ticket_id",
                    models.CharField(
                        blank=True,
                        help_text="External ticketing system ID (e.g., Jira)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="security_analysis.scan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finding",
                "verbose_name_plural": "Findings",
                "db_table": "findings",
                "ordering": ["-severity", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "status"],
                        name="findings_severit_c891a7_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="findings_created_5ddedc_idx"
                    ),
                ],
            },
        ),
    ]
