# Generated by Django 4.2.9 on 2025-10-23 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="External system ticket ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("JIRA", "Jira"),
                            ("SERVICENOW", "ServiceNow"),
                            ("MANUAL", "Manual"),
                        ],
                        help_text="Source system of the change request",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Change request title", max_length=255),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the change"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SECURITY_REVIEW", "Security Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the change request",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        help_text="Priority level",
                        max_length=20,
                    ),
                ),
                (
                    "requester",
                    models.CharField(
                        help_text="Person who requested the change", max_length=255
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(blank=True, help_text="Repository URL", null=True),
                ),
                (
                    "branch_name",
                    models.CharField(
                        blank=True, help_text="Branch name", max_length=255, null=True
                    ),
                ),
                (
                    "pull_request_url",
                    models.URLField(
                        blank=True, help_text="Pull request URL", null=True
                    ),
                ),
                (
                    "jenkins_build_url",
                    models.URLField(
                        blank=True, help_text="Jenkins build URL", null=True
                    ),
                ),
                (
                    "external_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data from external system",
                    ),
                ),
                (
                    "requested_date",
                    models.DateTimeField(
                        help_text="Date when the change was requested"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, help_text="Due date for the change", null=True
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when the change was completed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="AppSec engineer assigned to review",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Request",
                "verbose_name_plural": "Change Requests",
                "db_table": "change_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeRequestComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Comment content")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, help_text="Whether this is an internal comment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="change_requests.changerequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_request_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Request Comment",
                "verbose_name_plural": "Change Request Comments",
                "db_table": "change_request_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeRequestAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Attached file", upload_to="change_requests/%Y/%m/%d/"
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="change_requests.changerequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Request Attachment",
                "verbose_name_plural": "Change Request Attachments",
                "db_table": "change_request_attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="changerequest",
            index=models.Index(
                fields=["external_id", "source"], name="change_requ_externa_f3c899_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="changerequest",
            index=models.Index(
                fields=["status", "priority"], name="change_requ_status_dc8c3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="changerequest",
            index=models.Index(
                fields=["-created_at"], name="change_requ_created_64de02_idx"
            ),
        ),
    ]
