# Generated by Django 4.2.9 on 2025-10-23 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Integration name", max_length=100),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("JIRA", "Jira"),
                            ("SERVICENOW", "ServiceNow"),
                            ("GITHUB", "GitHub"),
                            ("GITLAB", "GitLab"),
                            ("JENKINS", "Jenkins"),
                            ("SONARQUBE", "SonarQube"),
                            ("SNYK", "Snyk"),
                            ("CHECKMARX", "Checkmarx"),
                            ("VERACODE", "Veracode"),
                        ],
                        help_text="Integration type",
                        max_length=20,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(help_text="Base URL of the external system"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this integration is active"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Integration configuration (encrypted credentials, etc.)",
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable bidirectional sync"
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.IntegerField(
                        default=15, help_text="Sync interval in minutes"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful sync timestamp",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "db_table": "integrations",
                "ordering": ["name"],
                "unique_together": {("name", "type")},
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Webhook name", max_length=100)),
                ("url", models.URLField(help_text="Webhook URL")),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of events to trigger this webhook"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this webhook is active"
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Webhook secret for signature verification",
                        max_length=255,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom headers to send with webhook",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "db_table": "webhooks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial Success"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "records_synced",
                    models.IntegerField(
                        default=0, help_text="Number of records synced"
                    ),
                ),
                (
                    "records_failed",
                    models.IntegerField(
                        default=0, help_text="Number of records that failed to sync"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, help_text="Sync duration in seconds", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if sync failed"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional sync details"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="integrations.integration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "db_table": "sync_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
